version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-nodejs
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_app
    ports:
     - "3306:3306"  
    volumes:
    # Mysql
    - db:/var/lib/mysql
    networks: 
      - nodejss

  web:
    depends_on:
      - mysql
    build: .
    ports: 
     - "3000:3000"
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    restart: unless-stopped
    container_name: nodejs
    stdin_open: true
    tty: true
    networks: 
      - nodejss

volumes:
  db:

networks:
  nodejss: